/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_loginWithPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_liveProbe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DriversController_findAll"];
        put?: never;
        post: operations["DriversController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DriversController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DriversController_provision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DriversController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DriversController_update"];
        trace?: never;
    };
    "/api/v1/drivers/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DriversController_approve"];
        trace?: never;
    };
    "/api/v1/drivers/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DriversController_suspend"];
        trace?: never;
    };
    "/api/v1/drivers/{id}/vehicle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DriversController_assignVehicle"];
        trace?: never;
    };
    "/api/v1/drivers/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DriversController_updateStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DriversController_updateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VehiclesController_findAll"];
        put?: never;
        post: operations["VehiclesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VehiclesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["VehiclesController_update"];
        trace?: never;
    };
    "/api/v1/vehicles/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["VehiclesController_updateStatus"];
        trace?: never;
    };
    "/api/v1/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RidesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RidesController_findHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RidesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RidesController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/arrived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RidesController_markArrived"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RidesController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RidesController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DispatchController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rides/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DispatchController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispatch/offers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DispatchOffersController_myPendingOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeviceTokensController_register"];
        delete: operations["DeviceTokensController_unregister"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maps/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MapsController_getRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CampusLocationsController_findAll"];
        put?: never;
        post: operations["CampusLocationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CampusLocationsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["CampusLocationsController_remove"];
        options?: never;
        head?: never;
        patch: operations["CampusLocationsController_update"];
        trace?: never;
    };
    "/api/v1/campus/roads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CampusRoadsController_findAll"];
        put?: never;
        post: operations["CampusRoadsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/roads/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["CampusRoadsController_setActive"];
        trace?: never;
    };
    "/api/v1/campus/restricted-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CampusRestrictedZonesController_findAll"];
        put?: never;
        post: operations["CampusRestrictedZonesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/restricted-zones/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["CampusRestrictedZonesController_setActive"];
        trace?: never;
    };
    "/api/v1/admin/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_listRides"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/live-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_getLiveMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @description Firebase ID token obtained client-side after Phone-OTP or Google Sign-In */
            idToken: string;
        };
        TokenResponseDto: {
            accessToken: string;
            refreshToken: string;
            role: string;
            userId: string;
        };
        RegisterDto: {
            /** @example Jane Doe */
            name: string;
            /**
             * @description E.164-ish mobile number - the primary account identifier
             * @example +911234567890
             */
            mobile: string;
            /** @example jane@example.com */
            email?: string;
            password: string;
        };
        PasswordLoginDto: {
            /**
             * @description Mobile number or email
             * @example +911234567890 or jane@example.com
             */
            identifier: string;
            password: string;
        };
        RefreshDto: {
            /** @description Refresh token issued at login */
            refreshToken: string;
        };
        UserResponseDto: {
            id: string;
            name: string;
            mobile: string;
            email: string | null;
            /** @enum {string} */
            role: "USER" | "DRIVER" | "ADMIN" | "OPERATOR";
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "PENDING";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UsersListResponseDto: {
            items: components["schemas"]["UserResponseDto"][];
            total: number;
        };
        CreateDriverDto: {
            /** @description Existing user id (must already exist, e.g. via OTP self-registration) */
            userId: string;
            /** @example DRV-001 */
            driverCode: string;
        };
        DriverResponseDto: {
            id: string;
            userId: string;
            driverCode: string;
            /** @enum {string} */
            status: "PENDING" | "ACTIVE" | "SUSPENDED" | "INACTIVE";
            /** @enum {string} */
            availability: "OFFLINE" | "AVAILABLE" | "BUSY" | "ON_BREAK";
            currentVehicleId: string | null;
            currentLatitude: number | null;
            currentLongitude: number | null;
            /** Format: date-time */
            locationUpdatedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProvisionDriverDto: {
            /** @example Ravi Kumar */
            name: string;
            /**
             * @description E.164-ish mobile number
             * @example +911234567890
             */
            mobile: string;
            /**
             * @description If set, login credentials are emailed here (best-effort)
             * @example ravi@example.com
             */
            email?: string;
            /** @example DRV-001 */
            driverCode: string;
            /** @description Assign a vehicle to the driver immediately, if already known */
            vehicleId?: string;
        };
        ProvisionDriverResponseDto: {
            driver: components["schemas"]["DriverResponseDto"];
            temporaryPassword: string;
            /** @description Whether the credentials email was actually sent (false if no email was given, or RESEND_API_KEY is unconfigured, or the send failed) */
            emailSent: boolean;
        };
        UpdateDriverDto: {
            /** @example DRV-001 */
            driverCode?: string;
        };
        AssignVehicleDto: {
            vehicleId: string;
        };
        UpdateAvailabilityDto: {
            /** @enum {string} */
            availability: "OFFLINE" | "AVAILABLE" | "ON_BREAK";
        };
        UpdateLocationDto: {
            latitude: number;
            longitude: number;
        };
        CreateVehicleDto: {
            /** @example EV-01 */
            vehicleCode: string;
            registrationNumber?: string;
            /** @default EV */
            vehicleType: string;
            /** @default 4 */
            capacity: number;
        };
        VehicleResponseDto: {
            id: string;
            vehicleCode: string;
            registrationNumber: string | null;
            vehicleType: string;
            capacity: number;
            /** @enum {string} */
            status: "AVAILABLE" | "IN_SERVICE" | "MAINTENANCE" | "INACTIVE";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateVehicleStatusDto: {
            /** @enum {string} */
            status: "AVAILABLE" | "IN_SERVICE" | "MAINTENANCE" | "INACTIVE";
        };
        UpdateVehicleDto: {
            /** @example EV-01 */
            vehicleCode?: string;
            registrationNumber?: string;
            vehicleType?: string;
            capacity?: number;
        };
        CreateRideDto: {
            pickupLatitude: number;
            pickupLongitude: number;
            pickupLocationName?: string;
            destinationLatitude: number;
            destinationLongitude: number;
            destinationLocationName?: string;
        };
        RideResponseDto: {
            id: string;
            userId: string;
            driverId: string | null;
            vehicleId: string | null;
            pickupLatitude: number;
            pickupLongitude: number;
            pickupLocationName: string | null;
            destinationLatitude: number;
            destinationLongitude: number;
            destinationLocationName: string | null;
            /** @enum {string} */
            status: "REQUESTED" | "SEARCHING_DRIVER" | "DRIVER_ASSIGNED" | "DRIVER_EN_ROUTE_TO_PICKUP" | "DRIVER_ARRIVED" | "RIDE_STARTED" | "DRIVER_EN_ROUTE_TO_DESTINATION" | "COMPLETED" | "CANCELLED_BY_USER" | "CANCELLED_BY_DRIVER" | "CANCELLED_BY_SYSTEM" | "NO_DRIVER_AVAILABLE";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            acceptedAt: string | null;
            /** Format: date-time */
            driverArrivedAt: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CancelRideDto: {
            reason?: string;
        };
        RegisterDeviceTokenDto: {
            /** @description The FCM registration token for this device. */
            token: string;
            /** @enum {string} */
            platform: "ANDROID" | "IOS";
        };
        DeviceTokenResponseDto: {
            id: string;
            userId: string;
            token: string;
            /** @enum {string} */
            platform: "ANDROID" | "IOS";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UnregisterDeviceTokenDto: {
            /** @description The FCM registration token to remove for the calling user. */
            token: string;
        };
        RouteManeuverResponseDto: {
            instruction: string;
            verbalPreTransitionInstruction?: string;
            verbalTransitionAlertInstruction?: string;
            verbalPostTransitionInstruction?: string;
            length: number;
            time: number;
            beginShapeIndex: number;
            endShapeIndex: number;
        };
        RouteResponseDto: {
            /** @description Encoded polyline, 1e6 precision (Valhalla default) */
            shape: string;
            /** @description Kilometers */
            length: number;
            /** @description Seconds */
            time: number;
            maneuvers: components["schemas"]["RouteManeuverResponseDto"][];
        };
        CreateCampusLocationDto: {
            /** @example Main Gate */
            name: string;
            /** @enum {string} */
            type: "GATE" | "BUILDING" | "OFFICE" | "RESIDENCE" | "DINING" | "PARKING" | "EV_STOP" | "MEDICAL" | "RECEPTION" | "OTHER";
            latitude: number;
            longitude: number;
            description?: string;
        };
        CampusLocationResponseDto: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "GATE" | "BUILDING" | "OFFICE" | "RESIDENCE" | "DINING" | "PARKING" | "EV_STOP" | "MEDICAL" | "RECEPTION" | "OTHER";
            latitude: number;
            longitude: number;
            description: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateCampusLocationDto: {
            name?: string;
            /** @enum {string} */
            type?: "GATE" | "BUILDING" | "OFFICE" | "RESIDENCE" | "DINING" | "PARKING" | "EV_STOP" | "MEDICAL" | "RECEPTION" | "OTHER";
            latitude?: number;
            longitude?: number;
            description?: string;
            isActive?: boolean;
        };
        GeoJsonLineStringDto: {
            /** @enum {string} */
            type: "LineString";
            /** @description Array of [longitude, latitude] pairs, at least 2 points */
            coordinates: unknown[][];
        };
        CreateCampusRoadDto: {
            /** @example Service road behind Dining Hall */
            name: string;
            geometry: components["schemas"]["GeoJsonLineStringDto"];
        };
        CampusRoadResponseDto: {
            id: string;
            name: string;
            geometry: components["schemas"]["GeoJsonLineStringDto"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateActiveDto: {
            isActive: boolean;
        };
        GeoJsonPolygonDto: {
            /** @enum {string} */
            type: "Polygon";
            /** @description Array of linear rings; each ring is an array of [longitude, latitude] pairs, first = last point */
            coordinates: unknown[][];
        };
        CreateCampusRestrictedZoneDto: {
            /** @example Dining plaza - event closure */
            name: string;
            reason?: string;
            geometry: components["schemas"]["GeoJsonPolygonDto"];
        };
        CampusRestrictedZoneResponseDto: {
            id: string;
            name: string;
            reason: string | null;
            geometry: components["schemas"]["GeoJsonPolygonDto"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        VehicleStatusCountsDto: {
            AVAILABLE: number;
            IN_SERVICE: number;
            MAINTENANCE: number;
            INACTIVE: number;
        };
        DriverAvailabilityCountsDto: {
            OFFLINE: number;
            AVAILABLE: number;
            BUSY: number;
            ON_BREAK: number;
        };
        DashboardSummaryResponseDto: {
            vehiclesByStatus: components["schemas"]["VehicleStatusCountsDto"];
            driversByAvailability: components["schemas"]["DriverAvailabilityCountsDto"];
            activeRidesCount: number;
        };
        AdminRidesListResponseDto: {
            items: components["schemas"]["RideResponseDto"][];
            total: number;
        };
        LiveMapDriverResponseDto: {
            driverId: string;
            driverCode: string;
            /** @enum {string} */
            availability: "OFFLINE" | "AVAILABLE" | "BUSY" | "ON_BREAK";
            latitude: number;
            longitude: number;
            /** Format: date-time */
            locationUpdatedAt: string | null;
            activeRideId: string | null;
            activeRideStatus: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_loginWithPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: {
                role?: "USER" | "DRIVER" | "ADMIN" | "OPERATOR";
                search?: string;
                /** @description Clamped to [1, 200]. */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersListResponseDto"];
                };
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_liveProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DriversController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"][];
                };
            };
        };
    };
    DriversController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDriverDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_provision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisionDriverDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisionDriverResponseDto"];
                };
            };
        };
    };
    DriversController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDriverDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_suspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_assignVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignVehicleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    DriversController_updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverResponseDto"];
                };
            };
        };
    };
    VehiclesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"][];
                };
            };
        };
    };
    VehiclesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
        };
    };
    VehiclesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
        };
    };
    VehiclesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
        };
    };
    VehiclesController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
        };
    };
    RidesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRideDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    RidesController_findHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"][];
                };
            };
        };
    };
    RidesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    RidesController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRideDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    RidesController_markArrived: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    RidesController_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    RidesController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RideResponseDto"];
                };
            };
        };
    };
    DispatchController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DispatchController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DispatchOffersController_myPendingOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeviceTokensController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceTokenResponseDto"];
                };
            };
        };
    };
    DeviceTokensController_unregister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnregisterDeviceTokenDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MapsController_getRoute: {
        parameters: {
            query: {
                originLat: number;
                originLng: number;
                destinationLat: number;
                destinationLng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
        };
    };
    CampusLocationsController_findAll: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusLocationResponseDto"][];
                };
            };
        };
    };
    CampusLocationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusLocationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusLocationResponseDto"];
                };
            };
        };
    };
    CampusLocationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusLocationResponseDto"];
                };
            };
        };
    };
    CampusLocationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CampusLocationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCampusLocationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusLocationResponseDto"];
                };
            };
        };
    };
    CampusRoadsController_findAll: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRoadResponseDto"][];
                };
            };
        };
    };
    CampusRoadsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusRoadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRoadResponseDto"];
                };
            };
        };
    };
    CampusRoadsController_setActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRoadResponseDto"];
                };
            };
        };
    };
    CampusRestrictedZonesController_findAll: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRestrictedZoneResponseDto"][];
                };
            };
        };
    };
    CampusRestrictedZonesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampusRestrictedZoneDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRestrictedZoneResponseDto"];
                };
            };
        };
    };
    CampusRestrictedZonesController_setActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActiveDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusRestrictedZoneResponseDto"];
                };
            };
        };
    };
    AdminController_getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponseDto"];
                };
            };
        };
    };
    AdminController_listRides: {
        parameters: {
            query?: {
                status?: "REQUESTED" | "SEARCHING_DRIVER" | "DRIVER_ASSIGNED" | "DRIVER_EN_ROUTE_TO_PICKUP" | "DRIVER_ARRIVED" | "RIDE_STARTED" | "DRIVER_EN_ROUTE_TO_DESTINATION" | "COMPLETED" | "CANCELLED_BY_USER" | "CANCELLED_BY_DRIVER" | "CANCELLED_BY_SYSTEM" | "NO_DRIVER_AVAILABLE";
                userId?: string;
                driverId?: string;
                /** @description ISO 8601 - filters rides.requestedAt >= this value */
                requestedAfter?: string;
                /** @description ISO 8601 - filters rides.requestedAt <= this value */
                requestedBefore?: string;
                /** @description Clamped to [1, 200]. */
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRidesListResponseDto"];
                };
            };
        };
    };
    AdminController_getLiveMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMapDriverResponseDto"][];
                };
            };
        };
    };
}
