apiVersion: v1
kind: PersistentVolume
metadata:
  name: sevarath-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /apps/sevarath/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sevarath-pvc
  namespace: sevarath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: sevarath-pv
