apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sevarath-ingress
  namespace: sevarath
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sevarath.rajendrakhope.com
    secretName: tls-sevarath.rajendrakhope.com
  rules:
  - host: sevarath.rajendrakhope.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sevarath-api
            port:
              number: 3000
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: sevarath-api
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sevarath-admin
            port:
              number: 80
