apiVersion: v1
kind: Service
metadata:
  name: sevarath-martin
  namespace: sevarath
  labels:
    app: sevarath-martin
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: sevarath-martin
